### ISSUE TITLE
I need your database to try the code

### ISSUE THREAD

**Issue by b2bviet** [sakibnazmus/shokherArot-socialSite#1]
I like your code and try to run your code in my server, but i do not find the database. Please post the database of the code if you want to share. Thank

**Comment by sakibnazmus** [comment]
> 
> 
> I like your code and try to run your code in my server, but i do not find the database. Please post the database of the code if you want to share. Thank

Sorry for the late reply. Haven't checked this repository for quite a long time now. If you are still interested, ping me at my email id: nazmus.sakib.czs2012@gmail.com

**Comment by b2bviet** [comment]
Dear friend,

I would thank for your reply my request at website github.com. I am sorry
because long time I do not check my request and check my email so that I do
not know your reply.

Now, one more time,  I would like to check your shokherarot-socialsite code
again  I hope you can give me the database of the code, and give me the
permission to change the code to use with my website.

I would like to hear your opinion.

Best regards,
Phat Nguyen

**Comment by sakibnazmus** [comment]
Dear Phat Nguyen,
This project was our college course project. We just hosted this website and database on a free hosting site.  And they archived it after a year. So currently I don't have that database.

I am really sorry to disappoint you. Please let me know if I can help you in any other way. Also I may up this website again after a few days. I will let you know then.

Regards,
Nazmus Sakib

**Comment by b2bviet** [comment]
Dear Sakibnazmus,

I am thank you for your reply, if you have any data schema of database, please give me the schema, I will try to run your code on my wamp server.

Regards,
Phat Nguyen

**Comment by sakibnazmus** [comment]
Dear Phat Nguyen,
I have lost my older database and had to rebuild it again. I tested it on local server and it seems to working fine. There might still be some bugs left. Please let me know if you find them and I will fix them accordingly. 

Thank You.

Regards,
Nazmus Sakib

**Comment by b2bviet** [comment]
Dear  Nazmus Sakib,

I would thank for your support, I will try your code, and inform you more
bug if i find them.

Best Regards,
Phat Nguyen

Vào Th 3, 13 thg 10, 2020 vào lúc 18:06 sakibnazmus <
notifications@github.com> đã viết:

**Comment by b2bviet** [comment]
Dear  Nazmus Sakib,

Can you help me to customize the shokherarot code?

I would like to change the code as follow:
- Add category for product posting
-Add Instant chat to discuss
- Add more attribute for product: buy,sell, rent, for rent
- Add Admin to control the website

I would like to hear your opinion.

Best regards,
Phat Nguyen


Vào CN, 18 thg 10, 2020 vào lúc 11:11 Phat Nguyen <nhphatvn@gmail.com> đã
viết:

**Comment by sakibnazmus** [comment]
Dear Phat Nguyen,
You suggested some interesting features to improve this project. However, I have been out of touch of PHP since this project. But I have been lately rebuilding this project using java spring framework. I had only developed the rest api so far. If you are interested, I can share that repository with you. 

Best regards,
Nazmus Sakib

**Comment by sakibnazmus** [comment]
Also, can we connect via linkedIn? 
I think linkedIn would be a better platform to communicate :)

**Comment by b2bviet** [comment]
Dear  Nazmus Sakib,

Please share me the repository, I like to try your project.

I will rebuild my linkedln account now, because long time i did not use my
account.

I will contact you later.

Best Regards,
Phat Nguyen

Vào Th 2, 30 thg 11, 2020 vào lúc 12:42 sakibnazmus <
notifications@github.com> đã viết:

**Comment by sakibnazmus** [comment]
Dear Phat Nguyen,
You can check out that repository with [this url](https://github.com/sakibnazmus/shokherArot)
I have made it public.

Regards,
Nazmus Sakib

**Comment by b2bviet** [comment]
Dear  Nazmus Sakib,
You do not post url link, please check again.

Best Regards,
Phat Nguyen

Vào Th 5, 3 thg 12, 2020 vào lúc 13:48 sakibnazmus <
notifications@github.com> đã viết:

**Comment by sakibnazmus** [comment]
https://github.com/sakibnazmus/shokherArot
